name: test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ubuntu-container:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out source
        uses: actions/checkout@v6
      - name: Test H0 and H1 in Ubuntu 26.04
        run: ./container-test
